version: '2.1'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    env_file: ../.env
    entrypoint: ruby /exercism/docker/entrypoint.rb
    volumes:
      - ..:/exercism
    environment:
      HOST_USER: $USER
